server:
  port: 8282
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: batalha-api  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     
